<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>csv</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~C</string>
	<key>name</key>
	<string>CSV</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#table</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>field</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(^|(?&lt;=,))(")</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.field.csv</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>
						this field uses "s and is thus able to enclose
						newlines or commas
					</string>
					<key>contentName</key>
					<string>meta.tabular.field.quoted.csv</string>
					<key>end</key>
					<string>(")($|(,))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.field.csv</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.tabular.field.csv</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>""</string>
							<key>name</key>
							<string>constant.character.escape.straight-quote.csv</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(:^|(?&lt;=,))(?!$|,)</string>
					<key>contentName</key>
					<string>meta.tabular.field.csv</string>
					<key>end</key>
					<string>$|(,)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.tabular.field.csv</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.tabular.field.csv</string>
				</dict>
			</array>
		</dict>
		<key>header</key>
		<dict>
			<key>begin</key>
			<string>^(?!$)</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.tabular.row.header.csv</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#field</string>
				</dict>
			</array>
		</dict>
		<key>row</key>
		<dict>
			<key>begin</key>
			<string>^(?!$)</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.tabular.row.csv</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#field</string>
				</dict>
			</array>
		</dict>
		<key>table</key>
		<dict>
			<key>begin</key>
			<string>^</string>
			<key>end</key>
			<string>^$not possible$^</string>
			<key>name</key>
			<string>meta.tabular.table.csv</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#header</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\n)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.table.row.csv</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>
						everything after the first row is not a header
					</string>
					<key>end</key>
					<string>^$not possible$^</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#row</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\n</string>
							<key>name</key>
							<string>punctuation.separator.table.row.csv</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.tabular.csv</string>
	<key>uuid</key>
	<string>B0691F9F-D279-48CB-8959-2C9426579002</string>
</dict>
</plist>
