source "https://rubygems.org"

gem "git"
gem "lucene", "~>0.5.0.beta.1"
gem "jruby-openssl"
gem "ruby-blockcache"
gem "bouncy-castle-java"
gem "swt"
gem "plugin_manager"
gem "redcar-xulrunner-win"
gem "zip"
gem "json"
gem "ffi"
