#! /usr/bin/env ruby

require File.dirname(__FILE__) + '/lib/redcar'
begin
 # Redcar::Colourer.debug = true
  Redcar.startup(:output => :silent)
  Gtk.main
rescue => e
  $stderr.puts <<ERR
---------------------------
Redcar has crashed.
---------------------------
Check #filename for backups of your documents. Redcar will 
notice these backups and prompt for recovery if you restart.

Please report this error message to the Redcar mailing list, along
with the actions you were taking at the time:

Time: #{Time.now}
Message: #{e.message}
Backtrace: \n#{e.backtrace.map{|l| "    "+l}.join("\n")}
Uname -a: #{`uname -a`.chomp}
ERR
  exit 1
end
