#!/usr/local/bin/ruby -Ku

require File.dirname(__FILE__) + '/lib/redcar'
begin
  Redcar.startup(:output => :silent)
  #Redcar::Syntax::Parser.debug = true
  #Redcar::SyntaxSourceView.debug = true
  #Redcar::Colourer.debug = true
  #Redcar::Theme.debug = true
  Gtk.main
rescue => e
  $stderr.puts str=<<ERR
---------------------------
Redcar has crashed.
---------------------------
Check #filename for backups of your documents. Redcar will 
notice these backups and prompt for recovery if you restart.

Please report this error message to the Redcar mailing list, along
with the actions you were taking at the time:

Time: #{Time.now}
Message: #{e.message}
Backtrace: \n#{e.backtrace.map{|l| "    "+l}.join("\n")}
Uname -a: #{`uname -a`.chomp}
ERR
  exit 1
end
