<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ssh_config</string>
		<string>.ssh/config</string>
		<string>sshd_config</string>
	</array>
	<key>name</key>
	<string>SSH Config</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(AddressFamily|B(atchMode|indAddress)|C(hallengeResponseAuthentication|heckHostIP|iphers?|learAllForwardings|ompression(Level)?|onnect(Timeout|ionAttempts)|ontrolMaster|ontrolPath)|DynamicForward|E(nableSSHKeysign|scapeChar)|Forward(Agent|X11(Trusted)?)|G(SSAPI(Authentication|DelegateCredentials)|atewayPorts|lobalKnownHostsFile)|Host(KeyAlgorithms|KeyAlias|Name|basedAuthentication)|Identit(iesOnly|yFile)|L(ocalForward|ogLevel)|MACs|N(oHostAuthenticationForLocalhost|umberOfPasswordPrompts)|P(asswordAuthentication|ort|referredAuthentications|rotocol|roxyCommand|ubkeyAuthentication)|R(SAAuthentication|emoteForward|hostsRSAAuthentication)|S(erverAliveCountMax|erverAliveInterval|martcardDevice|trictHostKeyChecking)|TCPKeepAlive|U(sePrivilegedPort|ser(KnownHostsFile)?)|VerifyHostKeyDNS|XAuthLocation)\b</string>
			<key>name</key>
			<string>keyword.other.ssh-config</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.ssh-config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.ssh-config</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash.ssh-config</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.ssh-config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>((#).*$\n?)|((//).*$\n?)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.ssh-config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.ssh-config</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.toc-list.ssh-config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^| |\t)(Host)\s+((.*))$</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b</string>
			<key>name</key>
			<string>constant.numeric.ssh-config</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.ssh-config</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ssh-config</string>
	<key>uuid</key>
	<string>B273855C-59D3-4DF3-9B7C-E68E0057D315</string>
</dict>
</plist>
