<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>foldingStartMarker</key>
	<string>^[ ]*(?x)
		(&lt;(?i:FilesMatch|Files|DirectoryMatch|Directory|LocationMatch|Location|VirtualHost|IfModule|IfDefine|Perl)\b.*?&gt;
		)</string>
	<key>foldingStopMarker</key>
	<string>^[ ]*(?x)
		(&lt;/(?i:FilesMatch|Files|DirectoryMatch|Directory|LocationMatch|Location|VirtualHost|IfModule|IfDefine|Perl)&gt;
		)</string>
	<key>keyEquivalent</key>
	<string>^~A</string>
	<key>name</key>
	<string>mod_perl</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^=</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.mod_perl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^=cut</string>
			<key>name</key>
			<string>comment.block.documentation.apache-config.mod_perl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(PerlAddVar|PerlConfigRequire|PerlLoadModule|PerlModule|PerlOptions|PerlPassEnv|PerlPostConfigRequire|PerlRequire|PerlSetEnv|PerlSetVar|PerlSwitches|SetHandler|PerlOpenLogsHandler|PerlPostConfigHandler|PerlChildInitHandler|PerlChildExitHandler|PerlPreConnectionHandler|PerlProcessConnectionHandler|PerlInputFilterHandler|PerlOutputFilterHandler|PerlSetInputFilter|PerlSetOutputFilter|PerlPostReadRequestHandler|PerlTransHandler|PerlMapToStorageHandler|PerlInitHandler|PerlHeaderParserHandler|PerlAccessHandler|PerlAuthenHandler|PerlAuthzHandler|PerlTypeHandler|PerlFixupHandler|PerlResponseHandler|PerlLogHandler|PerlCleanupHandler|PerlInterpStart|PerlInterpMax|PerlInterpMinSpare|PerlInterpMaxSpare|PerlInterpMaxRequests|PerlInterpScope|PerlTrace)\b</string>
			<key>name</key>
			<string>support.constant.apache-config.mod_perl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(PerlHandler|PerlScript|PerlSendHeader|PerlSetupEnv|PerlTaintCheck|PerlWarn|PerlFreshRestart)\b</string>
			<key>name</key>
			<string>support.constant.apache-config.mod_perl_1.mod_perl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*((&lt;)(Perl)(&gt;))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.apache-config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.apache-config</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.apache-config</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.apache-config</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^\s*((&lt;/)(Perl)(&gt;))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.apache-config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.apache-config</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.apache-config</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.apache-config</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.perl-section.apache-config.mod_perl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.perl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>source.apache-config</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.apache-config.mod_perl</string>
	<key>uuid</key>
	<string>6A616B03-1053-49BF-830F-0F4E63DB2447</string>
</dict>
</plist>
