<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>firstLineMatch</key>
	<string>^\s*={2,}(.*)={2,}\s*$</string>
	<key>foldingStartMarker</key>
	<string>(&lt;(php|html|file|nowiki)&gt;|&lt;code(\s*.*)?&gt;)|/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>(&lt;/(code|php|html|file|nowiki)&gt;)|\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~D</string>
	<key>name</key>
	<string>DokuWiki</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#php</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#inline</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.dokuwiki</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.dokuwiki</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.dokuwiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.dokuwiki</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\(\(</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.dokuwiki</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)\)</string>
			<key>name</key>
			<string>comment.block.documentation.dokuwiki</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.heading.dokuwiki</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.heading.dokuwiki</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(={2,})(.*)(={2,})\s*$\n?</string>
			<key>name</key>
			<string>markup.heading.dokuwiki</string>
		</dict>
		<dict>
			<key>match</key>
			<string>~~NOTOC~~</string>
			<key>name</key>
			<string>keyword.other.notoc.dokuwiki</string>
		</dict>
		<dict>
			<key>match</key>
			<string>~~NOCACHE~~</string>
			<key>name</key>
			<string>keyword.other.nocache.dokuwiki</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*-{4,}\s*$</string>
			<key>name</key>
			<string>meta.separator.dokuwiki</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\\\\s</string>
			<key>name</key>
			<string>markup.other.paragraph.dokuwiki</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^((\t+)|( {2,}))(\*)</string>
			<key>captures</key>
			<dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list_item.dokuwiki</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>markup.list.unnumbered.dokuwiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^((\t+)|( {2,}))(-)</string>
			<key>captures</key>
			<dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list_item.dokuwiki</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>markup.list.numbered.dokuwiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^[|^]</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.table.dokuwiki</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>markup.other.table.dokuwiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\&lt;)(file|nowiki)(\&gt;)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.template.dokuwiki</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.dokuwiki</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.dokuwiki</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.dokuwiki</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&lt;\/)(\2)(\&gt;)</string>
			<key>name</key>
			<string>markup.raw.dokuwiki</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(%%|\'\')</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.dokuwiki</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\1</string>
			<key>name</key>
			<string>markup.raw.dokuwiki</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;)(html)(&gt;)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.template.block.dokuwiki</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.dokuwiki</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.dokuwiki</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.dokuwiki</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&lt;/)(html)(&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>^((\s\s)|(\t))[^\*\-].*$</string>
			<key>name</key>
			<string>markup.raw.dokuwiki</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\&lt;)(sub|sup|del)(\&gt;)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.template.dokuwiki</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.dokuwiki</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.dokuwiki</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.dokuwiki</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\&lt;/)(\2)(\&gt;)</string>
			<key>name</key>
			<string>markup.other.dokuwiki</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;)(code)(?:\s+[^&gt;]*)?(&gt;)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.template.code.dokuwiki</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.dokuwiki</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.dokuwiki</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.dokuwiki</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&lt;/)(code)(&gt;)</string>
			<key>name</key>
			<string>markup.raw.dokuwiki</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\*\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bold.dokuwiki</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*\*</string>
					<key>name</key>
					<string>markup.bold.dokuwiki</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.italic.dokuwiki</string>
						</dict>
					</dict>
					<key>end</key>
					<string>//</string>
					<key>name</key>
					<string>markup.italic.dokuwiki</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>__</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.underline.dokuwiki</string>
						</dict>
					</dict>
					<key>end</key>
					<string>__</string>
					<key>name</key>
					<string>markup.underline.dokuwiki</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.image.dokuwiki</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.dokuwiki</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.image.dokuwiki</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\{\{)(.+?)(\}\})</string>
					<key>name</key>
					<string>meta.image.inline.dokuwiki</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.dokuwiki</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.dokuwiki</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.dokuwiki</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\[\[)(.*?)(\]\])</string>
					<key>name</key>
					<string>meta.link.dokuwiki</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.dokuwiki</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.interwiki.dokuwiki</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.dokuwiki</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\[\[)([^\[\]]+\&gt;[^|\]]+)(\]\])</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.dokuwiki</string>
						</dict>
					</dict>
					<key>match</key>
					<string>((https?|telnet|gopher|wais|ftp|ed2k|irc)://[\w/\#~:.?+=&amp;%@!\-;,]+?(?=[.:?\-;,]*[^\w/\#~:.?+=&amp;%@!\-;,]))</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.dokuwiki</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.dokuwiki</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.dokuwiki</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&lt;)([\w0-9\-_.]+?@[\w\-]+\.[\w\-\.]+\.*[\w]+)(\&gt;)</string>
					<key>name</key>
					<string>meta.link.email.dokuwiki</string>
				</dict>
			</array>
		</dict>
		<key>php</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.php</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^\s*)?(?=&lt;php&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.embedded.leading.dokuwiki</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.embedded.php</string>
					<key>end</key>
					<string>(?&lt;=&lt;/php&gt;)(?!&lt;php&gt;)(\s*$\n?)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.embedded.trailing.dokuwiki</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>((&lt;)(php)(&gt;))</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.embedded.begin.dokuwiki</string>
								</dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>meta.tag.template.dokuwiki</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.dokuwiki</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.dokuwiki</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.dokuwiki</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>source.php</string>
							<key>end</key>
							<string>(((&lt;/))(php)(&gt;))</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.embedded.end.dokuwiki</string>
								</dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>meta.tag.template.dokuwiki</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.dokuwiki</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>source.php</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.dokuwiki</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.tag.dokuwiki</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.php</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.dokuwiki</string>
	<key>uuid</key>
	<string>862D8B02-501E-4205-9DA4-FB7CDA7AE3DA</string>
</dict>
</plist>
