<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tmpl</string>
	</array>
	<key>firstLineMatch</key>
	<string>&lt;(?i:TMPL)_.+?&gt;</string>
	<key>foldingStartMarker</key>
	<string>(&lt;(?i:(head|table|tr|div|style|script|ul|ol|form|dl))\b.*?&gt;|^ *&lt;(?i:TMPL_(?:LOOP|UNLESS|IF))\b(?!.*&lt;/(?i:TMPL_(?:LOOP|UNLESS|IF))&gt;))</string>
	<key>foldingStopMarker</key>
	<string>(&lt;/(?i:(head|table|tr|div|style|script|ul|ol|form|dl))&gt;|^ *&lt;/(?i:TMPL_(?:LOOP|UNLESS|IF)) *&gt;)</string>
	<key>keyEquivalent</key>
	<string>^~H</string>
	<key>name</key>
	<string>Perl HTML-Template</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#tmpl-container-tag</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>embedded-code</key>
		<dict/>
		<key>entities</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.html</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.html</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&amp;)([a-zA-Z0-9]+|#[0-9]+|#x[0-9a-fA-F]+)(;)</string>
					<key>name</key>
					<string>constant.character.entity.html</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&amp;</string>
					<key>name</key>
					<string>invalid.illegal.bad-ampersand.html</string>
				</dict>
			</array>
		</dict>
		<key>html-template-stuff</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?i:NAME|ESCAPE|DEFAULT|)\b</string>
					<key>name</key>
					<string>keyword.control.html-template</string>
				</dict>
				<dict>
					<key>match</key>
					<string>=</string>
					<key>name</key>
					<string>punctuation.separator.key-value.html-template</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword</string>
				</dict>
			</array>
		</dict>
		<key>keyword</key>
		<dict>
			<key>match</key>
			<string>\b([A-Za-z0-9_]+)</string>
			<key>name</key>
			<string>string.unquoted.html-template</string>
		</dict>
		<key>string-double-quoted</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html-template</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html-template</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.html-template</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-code</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
		</dict>
		<key>string-single-quoted</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html-template</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html-template</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.html-template</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-code</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
		</dict>
		<key>tmpl-container-tag</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>&lt;/?(?i:TMPL_(?:IF|UNLESS|ELSE|VAR|INCLUDE|LOOP))</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.html-template</string>
						</dict>
					</dict>
					<key>end</key>
					<string>&gt;</string>
					<key>name</key>
					<string>meta.tag.template.html-template</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#html-template-stuff</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;/?(?i:TMPL_(?!IF|UNLESS|ELSE|VAR|INCLUDE|LOOP))</string>
					<key>end</key>
					<string>&gt;</string>
					<key>name</key>
					<string>invalid.illegal.tag.template.html-template</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.html-template</string>
	<key>uuid</key>
	<string>79287EAC-597A-480D-974C-837440298571</string>
</dict>
</plist>
