<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ant.xml</string>
		<string>build.xml</string>
	</array>
	<key>firstLineMatch</key>
	<string>&lt;\!--ant--&gt;</string>
	<key>foldingStartMarker</key>
	<string>^\s*(&lt;[^!?%/](?!.+?(/&gt;|&lt;/.+?&gt;))|&lt;[!%]--(?!.+?--%?&gt;)|&lt;%[!]?(?!.+?%&gt;))</string>
	<key>foldingStopMarker</key>
	<string>^\s*(&lt;/[^&gt;]+&gt;|[/%]&gt;|--&gt;)\s*$</string>
	<key>keyEquivalent</key>
	<string>^~A</string>
	<key>name</key>
	<string>Ant</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>&lt;[!%]--</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.xml.ant</string>
				</dict>
			</dict>
			<key>end</key>
			<string>--%?&gt;</string>
			<key>name</key>
			<string>comment.block.xml.ant</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;target)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.target.xml.ant</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(/?&gt;)</string>
			<key>name</key>
			<string>meta.tag.target.xml.ant</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tagStuff</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;/?)(?:([-_a-zA-Z0-9]+)((:)))?([-_a-zA-Z0-9:]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.xml.ant</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.namespace.xml.ant</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.xml.ant</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.namespace.xml.ant</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.localname.xml.ant</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(/?&gt;)</string>
			<key>name</key>
			<string>meta.tag.xml.ant</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tagStuff</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.xml</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>doublequotedString</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.xml.ant</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.xml.ant</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.xml.ant</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#javaProperties</string>
				</dict>
			</array>
		</dict>
		<key>javaProperties</key>
		<dict>
			<key>begin</key>
			<string>\${</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.java-prop.begin.ant</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.java-prop.end.ant</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.java-props.embedded.ant</string>
		</dict>
		<key>singlequotedString</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.xml.ant</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.xml.ant</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.ant</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#javaProperties</string>
				</dict>
			</array>
		</dict>
		<key>tagStuff</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.namespace.xml.ant</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.xml.ant</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.namespace.xml.ant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.localname.xml.ant</string>
						</dict>
					</dict>
					<key>match</key>
					<string> (?:([-_a-zA-Z0-9]+)((:)))?([_a-zA-Z-]+)=</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#doublequotedString</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#singlequotedString</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.xml.ant</string>
	<key>uuid</key>
	<string>E1B78601-E584-4A7F-B011-A61710BFE035</string>
</dict>
</plist>
